import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Moricol Organic Health",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}


// import "./globals.css";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { SessionProvider } from "next-auth/react";
// import { getServerSession } from "next-auth/next";
// import authOptions from "./lib/authOptions";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Moricol Organic Health",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const session = getServerSession(authOptions);
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <SessionProvider session={session}>{children}</SessionProvider>
//       </body>
//     </html>
//   );
// }
